version: '3.9'

services:
  db:
    image: postgres:15
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      POSTGRES_DB: rinhaDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1800m'

networks:
  default:
    driver: bridge
    name: rinha
